### ISSUE TITLE
Hentai.exists

### ISSUE THREAD

**Issue by nibacar** [hentai-chan/hentai#104]
I'm not sure but the Hentai.exists method doesn't seem to return false

**Comment by hentai-chan** [comment]
Hi @nibacar,

the nhentai servers are currently experiencing an outage, which was probably caused by an increase in traffic. While the servers are down, virtually all methods in this library stop working as well. Therefore, there isn't really anything I can do about it.

**Comment by hentai-chan** [comment]
Update: Website appears to be up again (`curl -I https://nhentai.net/`), but I'll leave this issue open for another few days to see if anything changes as this site experienced various up-and-down periods over the last couple of days.
