### ISSUE TITLE
[ BUG ] Make Request Paramter Not Working

### ISSUE THREAD

**Issue by hentai-chan** [hentai-chan/hentai#14]
**Describe the bug**
The `make_request` paramter doesn't work if the CWD isn't set to the package's root directory.

**To Reproduce**
1. Install package with `pip install hentai`
2. Error message:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hentai-chan\AppData\Roaming\Python\Python38\site-packages\hentai\hentai.py", line 630, in get_random_id
    with open("./data/ids.csv", mode='r', encoding='utf-8') as file_handler:
FileNotFoundError: [Errno 2] No such file or directory: './data/ids.csv'
```
3. Code samples
```python
>>> from hentai import Utils
>>> Utils.get_random_id(make_request=False)
```

**Additional context**
Useful links that help you fix that error:
[1] [Python Docs on `importlib.resources`](https://docs.python.org/3/library/importlib.html#module-importlib.resources)
[2] [Read the Docs for `importlib_resources`](https://importlib-resources.readthedocs.io/en/latest/using.html)

The project's file system layout needs to adapt to these changes without breaking backwards compatibility. As laid down in commit c7046e01ebf20e24debf54ff81128bea9372def4, this is just an experimental feature so this bug fix is a low priority on my bucket list. For anyone else interested in fixing this issue, feel free to have a shot at it!

**Comment by AbhiiGatty** [comment]
@hentai-chan can you assign this to me?

**Comment by hentai-chan** [comment]
I am happy to assign you this issue. If you have any questions feel free to shoot me an email, for the time being I'll leave the rest up to you. Last but not least I want to point out that you need to add an unit test to `tests/test_utils.py` once your done so that I can accept your pull request. This parameter is used in multiple functions, but it suffices to just add one additional test function `test_random_id_with_param` to the test suite. Good luck!

**Comment by hysrx** [comment]
Have you considered using `Path(__file__).parent.absolute()`? It's what I use in my personal scripts to get the parent directory of my script. And pathlib is really dandy, so joining paths would look something like `Path(Path(__file__).parent.absolute(), 'data/ids.csv')`

If this turns out to be helpful - [here is a pathlib cheatsheet!](https://github.com/chris1610/pbpython/blob/master/extras/Pathlib-Cheatsheet.pdf)

**Comment by hentai-chan** [comment]
Thanks for this suggestion, @AbhiiGatty will investigate whether this help fix the bug by the end of this month, though I think it's better to use `Path(__file__).parent.absolute().joinpath('data/ids.csv')` for joining paths. I also need to find a way to keep this `ids.csv` up-to-date, best case scenario I find a way to populate this file with making less requests.

**Comment by hentai-chan** [comment]
@hysrx My last commit should have fixed this issue, I leveraged the standard library that's in charge of importing static resources. Basically, you create a new directory for your resource in the source directory of your code (in this case, `hentai/data`). Then you add an empty `__init__.py`  file to declare this folder as a subpackage to be able to import it like this:

```python
from importlib.resources import path as resource_path

with resource_path('hentai.data', 'ids.csv') as data_path:
    print(f"Hi, my path is {data_path}!")
```

So, now you can run

```python
>>> from hentai import Hentai; Hentai.exists(177013, make_request=False)
True
```

which checks the `data.csv` for proof of existence. Although this collection is incomplete, I will try to add the remaining ids by the end of next week. I would need to think about a way to automate this procedure as well. But on the plus side, this method is much faster especially if you need to check multiple ids in a loop at once.
